# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 03:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_voites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='voites',
        ),
    ]
